version: "3.7"
services:
  db:
    restart: always
    image: postgres:13.10-bullseye
    networks:
      - nextcloud
    ports:
      - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=postgres
#    - POSTGRES_MULTIPLE_DATABASES=nextcloud
    volumes:
    - ./postgres:/var/lib/postgresql/data
    - ./postgres_init/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
  nextcloud_backup:
    container_name: nextcloud_db_backup
    image: tiredofit/db-backup
    depends_on:
      - db
    volumes:
      - ./db_backups/:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    networks:
        nextcloud:
    environment:
      - DEBUG_MODE=TRUE
      - DB_TYPE=postgres
      - DB_HOST=db
      - DB_NAME=nextcloud
      - DB_USER=nextcloud
      - DB_PASS=nextcloud
      - DB_DUMP_FREQ=360          # backup 12 hours 12 * 60
#      - DB_DUMP_BEGIN="+10"        # backup starts immediately
      - DB_CLEANUP_TIME=72000     # clean backups that are older than 72000 minutes
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=true
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always

  redis:
    image: redis:6.0.16
    restart: always
    networks:
      - nextcloud
    volumes:
      - ./redis:/var/lib/redis
  nextcloud:
    image: nextcloud:27.0.2
    restart: always
    networks:
      - nextcloud
      - traefik-public
    depends_on:
      - redis
      - db
    ports:
      - 8888:80
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.heim.rule=Host(`nextcloud.fiks.im`)"
#      - "traefik.http.routers.heim.entrypoints=web"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`nextcloud.fiks.im`)"
#      - "traefik.http.routers.nextcloud-secure.middlewares=traefik-auth"
      - "traefik.http.routers.nextcloud-secure.tls=true"
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.fiks.im
      - TRUSTED_PROXIES=172.29.8.0/8
    volumes:
      - ./nextcloud:/var/www/html
#      - ./nextcloud/documents_storage:/var/www/html/data
networks:
  nextcloud:
  traefik-public:
    external: true
