server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

#client:
#  url: https://1111:eyJrIjoiY

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: testlog
      __path__: /var/log/ufw.log
