version: "3.7"

services:
  bitwardenrs:
    image: vaultwarden/server
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true
      # Comment admin token to disable admin interface
      - ADMIN_TOKEN=admin
      - YUBICO_CLIENT_ID=1111111
      - YUBICO_SECRET_KEY=22222222
    networks:
        traefik-public:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bitwarden.rule=Host(`vault.fiks.im`)"
      - "traefik.http.routers.bitwarden.entrypoints=web"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.bitwarden-secure.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-secure.rule=Host(`vault.fiks.im`)"
#      - "traefik.http.routers.bitwarden-secure.middlewares=traefik-auth"
      - "traefik.http.routers.bitwarden-secure.tls=true"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"

#      - "com.centurylinklabs.watchtower.enable=true"
#      # Ip filtering
#      - "traefik.http.routers.bitwarden.middlewares=whitelist@file"
    logging:
      driver: "syslog"
      options:
        tag: "Bitwarden"
networks:
  traefik-public:
    external: true
