version: '3.7'
services:
# Teedy Application
  teedy-server:
    image: sismics/docs:v1.11
#    ports:
#      # Map internal port to host
#      - 8080:8080
    environment:
      # Base url to be used
      DOCS_BASE_URL: "https://docs.fiks.im"
      # Set the admin email
      DOCS_ADMIN_EMAIL_INIT: "youremail@domain"
      # Set the admin password (compatiple with htpassword)
      DOCS_ADMIN_PASSWORD_INIT: "$$2a..."
      # Setup the database connection. "teedy-db" is the hostname
      # and "teedy" is the name of the database the application
      # will connect to.
      DATABASE_URL: "jdbc:postgresql://teedy-db:5432/teedy"
      DATABASE_USER: "teedy"
      DATABASE_PASSWORD: "teedy"
    networks:
        traefik-public:
        teedy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teedy.rule=Host(`docs.fiks.im`)"
      - "traefik.http.routers.teedy.entrypoints=web"
      - "traefik.http.services.teedy.loadbalancer.server.port=8080"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.teedy-secure.entrypoints=websecure"
      - "traefik.http.routers.teedy-secure.rule=Host(`docs.fiks.im`)"
#      - "traefik.http.routers.teedy-secure.middlewares=traefik-auth"
      - "traefik.http.routers.teedy-secure.tls=true"
    restart: always
    volumes:
      - ./docs/data:/data
    depends_on:
      - teedy-db

# DB for Teedy
  teedy-db:
    image: postgres:13.1-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: "teedy"
      POSTGRES_PASSWORD: "teedy"
      POSTGRES_DB: "teedy"
    networks:
        teedy:
    volumes:
      - ./docs/db:/var/lib/postgresql/data

  teedy_backup:
    container_name: teedy_db_backup
    image: tiredofit/db-backup
    depends_on:
      - teedy-db
    volumes:
      - ./docs/db_backups/:/backup
      #- ./post-script.sh:/assets/custom-scripts/post-script.sh
    networks:
        teedy:
    environment:
      - DEBUG_MODE=TRUE
      - DB_TYPE=postgres
      - DB_HOST=teedy-db
      - DB_NAME=teedy
      - DB_USER=teedy
      - DB_PASS=teedy
      - DB_DUMP_FREQ=360          # backup 12 hours 12 * 60
#      - DB_DUMP_BEGIN="+10"        # backup starts immediately
      - DB_CLEANUP_TIME=72000     # clean backups that are older than 72000 minutes
      - CHECKSUM=SHA1
      - COMPRESSION=GZ
      - SPLIT_DB=true
      - CONTAINER_ENABLE_MONITORING=FALSE
    restart: always
networks:
  traefik-public:
    external: true
  teedy:

