version: '3.3'

services:
  tubearchivist:
    container_name: tubearchivist
    restart: always
    image: bbilly1/tubearchivist
    networks:
      - traefik-public
      - tube
#    ports:
#      - 8000:8000
    volumes:
      - ./media:/youtube
      - ./cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tube.fiks.im      # set your host name
      - TA_USERNAME=admin                  # your initial TA credentials
      - TA_PASSWORD=admin              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=Europe/Kyiv                 # set your time zone
    depends_on:
      - archivist-es
      - archivist-redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tube.rule=Host(`tube.fiks.im`)"
      - "traefik.http.routers.tube.entrypoints=web"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.tube-secure.entrypoints=websecure"
      - "traefik.http.routers.tube-secure.rule=Host(`tube.fiks.im`)"
#      - "traefik.http.routers.whoami-secure.middlewares=traefik-auth"
      - "traefik.http.routers.tube-secure.tls=true"
      - "traefik.http.routers.tube-secure.tls.certresolver=le"

  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    networks:
      - tube
    restart: always
    expose:
      - "6379"
    volumes:
      - ./redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.7.0
    container_name: archivist-es
    restart: always
    networks:
      - tube
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

volumes:
  media:
  cache:
  redis:
  es:
networks:
  traefik-public:
    external: true
  tube:
