---
version: "3.7"
services:
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: tabix
    networks:
        traefik-public:
    extra_hosts:
        docker.lvh.voronenko.net: 172.19.0.1
        lvh.voronenko.net: 172.19.0.1
        clickhouse: 172.19.0.1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tabix.rule=Host(`tabix.lvh.voronenko.net`)"
      - "traefik.http.routers.tabix.entrypoints=web"
      - "traefik.http.services.tabix.loadbalancer.server.port=80"

#      - "traefik.http.middlewares.traefik-auth.basicauth.users=USER:PASSWORD"
#      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"

      - "traefik.http.routers.tabix-secure.entrypoints=websecure"
      - "traefik.http.routers.tabix-secure.rule=Host(`tabix.lvh.voronenko.net`)"
#      - "traefik.http.routers.heim-secure.middlewares=traefik-auth"
      - "traefik.http.routers.tabix-secure.tls=true"
    restart: unless-stopped
networks:
  traefik-public:
    external: true

